# Site settings
title: Max's Blog
SEOTitle: Max's Blog
header-img: img/blog_bg_homepage_2019_4.jpg
email: viywang@gmail.com
description: "Keep self busy."
keyword: "Max's Blog"
url: "http://VVViy.github.io"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/VVViy/VVViy.github.io.git" # you code repository


# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "It's not the gods' thing, it's people."
sidebar-avatar: /img/avatar-max.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`


# SNS settings
RSS: false
# zhihu_username:     VVViy
# github_
